a = input('digite algo: ')
print('o tipo primitivo desse valor e', type(a))
print('\33[;31mso tem espacos:',a.isspace())
print('\33[;32me um numero?',a.isnumeric())
print('\33[;33me alfabetico?',a.isalpha())
print('\33[;34mele eh alfanumerico?',a.isalnum())
print('\33[;35mesta em maiuscula?',a.isupper())
print('\33[;36mesta em minusculas?',a.islower())
print('\33[;37mesta capitalizada?',a.istitle())